# Generated by Django 4.0.4 on 2022-05-06 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last name')),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, max_length=50, null=True, verbose_name='Fecha de nacimiento')),
                ('password1', models.CharField(blank=True, max_length=50, null=True)),
                ('password2', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
